# Generated by Django 4.2.5 on 2024-02-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_injury_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
