# Generated by Django 4.2.5 on 2024-02-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='born_smelly',
        ),
        migrations.RemoveField(
            model_name='user',
            name='month_of_birth',
        ),
    ]
