# Generated by Django 4.2.4 on 2024-02-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
